apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dotnet-deployment
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: simple-dotnet
        image: 661025160735.dkr.ecr.us-east-1.amazonaws.com/demo-repo:v1
        ports:
        - containerPort: 80