apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
  - host: simple-dotnet.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-dotnet-service
          servicePort: 80

  - host: order.foodpanda.com
    http:
      paths:
      - path: /
        backend:
          serviceName: order-service
          servicePort: 80